# Generated by Django 2.0 on 2020-01-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200124_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.IntegerField(choices=[(1, 'Hospital'), (2, 'Vendor')], default=1, verbose_name='type'),
        ),
    ]
